#!/usr/bin/env python3
"""
推送项目到GitHub的脚本
使用用户名和密码进行认证
"""

import os
import subprocess
from pathlib import Path
from typing import Optional

def setup_git_and_push(github_user: str, github_password: str, repo_name: Optional[str] = None):
    """
    配置Git并将项目推送到GitHub，如果仓库不存在则创建
    
    Args:
        github_user: GitHub用户名
        github_password: GitHub密码或个人访问令牌
        repo_name: 仓库名称（默认为当前目录名）
    """
    print("配置Git并推送到GitHub...")
    
    # 确定仓库名称
    if repo_name is None:
        repo_name = Path("..").resolve().name
    
    repo_url_https = f"https://github.com/{github_user}/{repo_name}.git"
    repo_url_ssh = f"git@github.com:{github_user}/{repo_name}.git"
    api_url = f"https://api.github.com/repos/{github_user}/{repo_name}"
    
    # 尝试使用GitHub API检查仓库（使用基本认证）
    import requests
    auth = (github_user, github_password)
    headers = {
        "Accept": "application/vnd.github.v3+json"
    }
    
    api_success = False
    try:
        print(f"检查仓库 {github_user}/{repo_name} 是否存在...")
        response = requests.get(api_url, headers=headers, auth=auth, timeout=10)
        
        if response.status_code == 404:
            print("仓库不存在，正在创建...")
            # 创建仓库
            create_data = {
                "name": repo_name,
                "description": "Java Snake Game project",
                "private": False,
                "auto_init": False
            }
            create_response = requests.post(
                f"https://api.github.com/user/repos",
                headers=headers,
                auth=auth,
                json=create_data,
                timeout=10
            )
            if create_response.status_code in (201, 200):
                print(f"仓库 {repo_name} 创建成功")
            else:
                print(f"仓库创建失败: {create_response.status_code} - {create_response.text}")
                # 继续尝试推送，可能仓库已存在但权限不足
        elif response.status_code == 200:
            print("仓库已存在")
        else:
            print(f"检查仓库时出错: {response.status_code} - {response.text}")
            # 继续尝试推送
        api_success = True
    except Exception as e:
        print(f"GitHub API调用失败，将跳过仓库检查: {e}")
    
    # 初始化本地Git仓库（如果尚未初始化）
    if not os.path.exists("../.git"):
        print("初始化Git仓库...")
        subprocess.run(["git", "init"], cwd="..", check=True)
    
    # 配置远程仓库
    print("配置远程仓库...")
    # 移除可能已存在的远程仓库
    subprocess.run(["git", "remote", "remove", "origin"], cwd="..", capture_output=True)
    
    # 尝试使用HTTPS with password/token进行推送
    if api_success:
        try:
            auth_repo_url = f"https://{github_user}:{github_password}@github.com/{github_user}/{repo_name}.git"
            subprocess.run(["git", "remote", "add", "origin", auth_repo_url], cwd="..", check=True)
            print("使用HTTPS基本认证配置远程仓库")
        except Exception as e:
            print(f"HTTPS基本认证失败，尝试使用SSH: {e}")
            subprocess.run(["git", "remote", "remove", "origin"], cwd="..", capture_output=True)
            subprocess.run(["git", "remote", "add", "origin", repo_url_ssh], cwd="..", check=True)
            print("使用SSH配置远程仓库")
    else:
        # 直接使用SSH
        subprocess.run(["git", "remote", "add", "origin", repo_url_ssh], cwd="..", check=True)
        print("使用SSH配置远程仓库")
    
    # 添加所有文件并提交
    print("添加文件并提交...")
    subprocess.run(["git", "add", "."], cwd="..", check=True)
    # 检查是否有更改需要提交
    result = subprocess.run(["git", "status", "--porcelain"], cwd="..", capture_output=True, text=True)
    if result.stdout.strip():
        subprocess.run(["git", "commit", "-m", "Add project description generated by script"], 
                      cwd="..", check=True)
    else:
        print("没有更改需要提交")
    
    # 重命名分支为main（如果当前不是main）
    print("确保分支为main...")
    subprocess.run(["git", "branch", "-M", "main"], cwd="..", check=True)
    
    # 推送到GitHub
    print("推送到GitHub...")
    try:
        result = subprocess.run(["git", "push", "-u", "origin", "main"], cwd="..", capture_output=True, text=True, timeout=30)
        if result.returncode != 0:
            print(f"推送失败: {result.stderr}")
            # 尝试强制推送（如果历史不一致）
            print("尝试强制推送...")
            subprocess.run(["git", "push", "-f", "origin", "main"], cwd="..", check=True)
    except subprocess.TimeoutExpired:
        print("推送超时，可能网络问题")
        raise
    except Exception as e:
        print(f"推送失败: {e}")
        raise
    
    print(f"项目已成功推送到GitHub: {repo_url_https}")

def main():
    """主函数"""
    try:
        # 推送到GitHub
        github_user = "hzboom"
        github_password = "330127sw"
        setup_git_and_push(github_user, github_password)
        
        print("脚本执行完成！")
        
    except Exception as e:
        print(f"脚本执行失败: {e}")
        import traceback
        traceback.print_exc()
        exit(1)

if __name__ == "__main__":
    main()